# Generated by Django 2.1.2 on 2018-10-04 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181004_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Зөв дугаар оруулна уу.', regex='(9[0-9])[0-9]{6}|(8[0-9])[0-9]{6}|(7[0-9])[0-9]{6}$')]),
        ),
    ]
