# Generated by Django 2.1.2 on 2018-10-05 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Холбоос')),
                ('product_name', models.CharField(max_length=20, verbose_name='Барааны нэр')),
                ('product_count', models.PositiveSmallIntegerField(verbose_name='Тоо ширхэг')),
                ('size', models.CharField(choices=[('L', 'L'), ('M', 'M'), ('S', 'S'), ('XXXL', 'XXXL'), ('XXL', 'XXXL'), ('XL', 'XL'), ('XS', 'XS')], max_length=8, verbose_name='Хэмжээ')),
                ('color', models.CharField(max_length=15, verbose_name='Өнгө')),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(verbose_name='Хаяг')),
                ('status', models.CharField(choices=[('Захиалга илгээгдсэн', 'Захиалга илгээгдсэн'), ('Төлбөр хүлээгдэж байна', 'Төлбөр хүлээгдэж байна'), ('Төлбөр хийгдсэн', 'Төлбөр хийгдсэн'), ('Захиалга хийгдсэн', 'Захиалга хийгдсэн'), ('Захиалга хүргэгдсэн', 'Захиалга хүргэгдсэн')], default=('Захиалга илгээгдсэн', 'Захиалга илгээгдсэн'), max_length=25)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(verbose_name='Үнэ')),
                ('trans_cost', models.IntegerField(verbose_name='Тээврийн зардал')),
                ('trans_to_cost', models.IntegerField(verbose_name='Хятад - Улаанбаатар хотод ирэх тээврийн зардал')),
                ('service_fee', models.IntegerField(verbose_name='Үйлчилгээний хөлс')),
                ('exchange', models.IntegerField(verbose_name='Ханш')),
                ('total', models.FloatField(verbose_name='Нийт')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
