# Generated by Django 2.1.2 on 2018-10-05 05:34

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.IntegerField(default=order.models.unique_no, editable=False),
        ),
    ]
